version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: unimeet-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=unimeet
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: unimeet-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  # MongoDB 관리 도구 (선택사항)
  mongo-express:
    image: mongo-express:latest
    container_name: unimeet-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    restart: unless-stopped

  # Redis 관리 도구 (선택사항)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: unimeet-redis-commander
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  mongodb_data:
  redis_data: