version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    depends_on:
      - backend
    stdin_open: true
    tty: true

  backend:
    build: ./backend
    container_name: springboot-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb
      - redis
      - ai
    volumes:
      - ./backend:/app
      - /app/build

  ai:
    build:
      context: ./ai
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./ai:/app
    environment:
      - PYTHONPATH=/app
    depends_on: []

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=unimeet

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

networks:
  default:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: 