spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: unimeet
  redis:
    host: redis
    port: 6379

logging:
  level:
    org.springframework.security: INFO
    com.unimeet.backend: INFO
    root: WARN