server:
  port: 8080

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:unimeet}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:true}
  security:
    jwt:
      secret: ${JWT_SECRET:default-secret-key-for-development-only-change-in-production}
      expiration: ${JWT_EXPIRATION:86400000} # 24시간

ai:
  service:
    url: ${AI_SERVICE_URL:http://localhost:8001}
    enabled: ${AI_SERVICE_ENABLED:false}

logging:
  level:
    org.springframework.security: ${LOG_LEVEL_SECURITY:INFO}
    com.unimeet.backend: ${LOG_LEVEL_APP:INFO}
    root: ${LOG_LEVEL_ROOT:INFO} 